### ISSUE TITLE
Migrate Page builder content to cms pages

### ISSUE THREAD

**Issue by thomas-kl1** [opengento/magento2-downgrade-ee-ce#2]
In M2.3, the Page builder content can be easily migrated to classic Magento cms pages as it's plain html value in db

**Comment by FredericMartinez** [comment]
FYI Opensource Page Builder for M2 : https://github.com/magesuite/magesuite

**Comment by thomas-kl1** [comment]
@FredericMartinez Any idea what package to look for the DB structure?

**Comment by thomas-kl1** [comment]
Closing this issue because the Page Builder is now part of the Open-Source version.
